-- MySQL Script generated by MySQL Workbench
-- 11/03/14 17:08:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nqcms
-- -----------------------------------------------------
-- 40期CMS系统

-- -----------------------------------------------------
-- Schema nqcms
--
-- 40期CMS系统
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nqcms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `nqcms` ;

-- -----------------------------------------------------
-- Table `nqcms`.`hd_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nqcms`.`hd_category` (
  `cid` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `catname` CHAR(50) NOT NULL DEFAULT '' COMMENT '栏目名称',
  `pid` SMALLINT NOT NULL DEFAULT 0 COMMENT '父ID',
  `keywords` VARCHAR(100) NULL COMMENT '关键字',
  `description` VARCHAR(200) NULL COMMENT '栏目描述',
  `list_tpl` VARCHAR(255) NULL DEFAULT 'list.html' COMMENT '列表页模板',
  `content_tpl` VARCHAR(255) NULL DEFAULT 'content.html' COMMENT '详情页模板',
  PRIMARY KEY (`cid`))
ENGINE = MyISAM
COMMENT = '栏目表';


-- -----------------------------------------------------
-- Table `nqcms`.`hd_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nqcms`.`hd_content` (
  `aid` INT NOT NULL AUTO_INCREMENT,
  `title` CHAR(100) NULL,
  `content` TEXT NULL,
  `addtime` INT(10) NULL,
  `click` MEDIUMINT UNSIGNED NULL,
  `cid` SMALLINT UNSIGNED NOT NULL,
  `thumb` VARCHAR(255) NULL COMMENT '缩略图',
  `keywords` VARCHAR(100) NULL COMMENT '关键字',
  `description` VARCHAR(255) NULL COMMENT '描述',
  PRIMARY KEY (`aid`),
  INDEX `fk_hd_content_hd_category_idx` (`cid` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `nqcms`.`hd_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nqcms`.`hd_config` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '配置名',
  `value` VARCHAR(255) NULL COMMENT '值',
  `type` ENUM('text','radio','textarea') NULL COMMENT '显示类型:text/radio/textarea',
  `info` VARCHAR(255) NULL COMMENT '参数如:radio   1|开启,0|关闭',
  `title` VARCHAR(45) NULL COMMENT '中文描述',
  `orderlist` SMALLINT NULL COMMENT '排序',
  `isshow` TINYINT NULL COMMENT '网站配置是否显示',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
